### ISSUE TITLE
How to test on localhost

### ISSUE THREAD

**Issue by GoogleCodeExporter** [GrabzIt/grabzit#1]
```
http://grabz.it/api/aspnet/
states : "Remember this callback will not work if your application is located 
on localhost."

How can you develop and test your code locally then ?

I get a "Application Key not recognised." in the TakePicture() method of the 
GrabzItClient.cs class.
Yes, I declared both my ApplicationKey and ApplicationSecret in the web.config

Using version aspnet-1.1.1 in the Sample project converted to framework .NET 4 
in Visual Studio 2010.
```

Original issue reported on code.google.com by `oud...@gmail.com` on 18 Dec 2012 at 4:00

Attachments:
- [grabzit.png](https://storage.googleapis.com/google-code-attachments/grabzit/issue-1/comment-0/grabzit.png)

**Comment by jnelken** [comment]
You should keep this issue open so that other can find it easily. Use `save_to` instead of `save` to have it work well locally and on production/staging

**Comment by GrabzIt** [comment]
I will document this on the main API page of each language. For instance: https://grabz.it/api/java/
