### ISSUE TITLE
import grabzit in react

### ISSUE THREAD

**Issue by uragecz** [GrabzIt/grabzit#10]
Hi is there any way how to import grabzit in react through  - import ... from ... ?? I am using react, and when i just import <script src="/external_js/grabzit.mini.js"></script> into index.html. still i am getting error- `Uncaught ReferenceError: GrabzIt is not defined`

**Comment by GrabzIt** [comment]
GrabzIt is not a react package but a JavaScript library in the same way jQuery is, so you will have to reference it as normal. I would use your browser debugger to ensure it is being loaded correctly and that you have placed grabzit.min.js in the correct location.
