### ISSUE TITLE
Save fails with a POST in PHP when using cURL

### ISSUE THREAD

**Issue by slimtim** [GrabzIt/grabzit#11]
Making a POST request to the GrabzIt API (e.g. when saving HTML to PDF/Image/Docx/Table) fails in PHP when using cURL. Calling the SaveTo() method generates the warning:
PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found in GrabzItClient.class.php on line 690

To reproduce, generate a test.php file:
```
<?php
require_once 'vendor/autoload.php';

$key = '';
$secret = '';
$grabzIt = new GrabzItClient($key, $secret);

$html = '<html><body><p>This is a test</p></body></html>';
$grabzIt->HTMLToPDF($html);

$contents = $grabzIt->SaveTo();
```

Run the test file as:
`php -d allow_url_fopen=0 test.php`
// PHP warning occurs

**Comment by GrabzIt** [comment]
Thanks for the fix.
