### ISSUE TITLE
PHP: Use namespaces and PSR-4 autoloader

### ISSUE THREAD

**Issue by TorbenLundsgaard** [GrabzIt/grabzit#14]
The PHP library could be greatly improved by using namespaces and PSR-4 autoloading. I have it working in this fork: https://github.com/TorbenLundsgaard/grabzit-php

It requires that the library is installed with composer, so it is therefore not backwards compatible. I suggest that you prepare for a 4.0 release of the library and I’ll be happy to contribute any way I can.

**Comment by GrabzIt** [comment]
Thanks for this great contribution! We will investigate the best way to take this forward.

**Comment by TorbenLundsgaard** [comment]
I think that you should use https://github.com/GrabzIt/grabzit-php as the primary repository and then require it with composer in the demo in https://github.com/GrabzIt/grabzit/tree/master/php

You should create a 3.X branch in https://github.com/GrabzIt/grabzit-php and start preparing for 4.0 in the master branch of that repository.

You should consider starting to use PHPUnit tests and consider raising the PHP requirement to 5.6 or even 7.0.

As I said I’m willing to put in some time and help you.

**Comment by TorbenLundsgaard** [comment]
I have tested it and it works for me in my Symfony application.

There is one tiny bug in the file 'lib/GrabzItException.php'

This:
class GrabzItException extends Exception {

Should be:
class GrabzItException extends \Exception {

**Comment by TorbenLundsgaard** [comment]
I have just testet it again and I have not found any problems. I think it is ready for a new release.
