### ISSUE TITLE
DOCX issues converting nested tables

### ISSUE THREAD

**Issue by Mohini89** [GrabzIt/grabzit#19]
CSS for nested tables not working

**Comment by GrabzIt** [comment]
Sorry, for what conversion type? PDF, DOCX?  Also do you have a simple example we can see?

**Comment by Mohini89** [comment]
I am trying to convert HTML to Docx. Though it is working for PDF

**Comment by Mohini89** [comment]
**<div>
                <table style="width:100%;text-align: left;">
                    <tr>
                        <td>
                            <div style="float:left;margin-top:123px;">
                                <div style="font-size:18px; font-weight:bold;text-decoration: underline;"> {{TEXT}}</div>
                                <div style="font-size:20px;"> {{TEXT}}:</div>
                            </div>
                        </td>
                        <td>
                            <table class="tablecode" id="tablecode"  style="width:100%;text-align: left;">
                                <tr>
                                    <td>Account<br> Manager Name:</td>
                                    <td>{{TEXT}}</td>
                                </tr>
                                <tr>
                                    <td>Email</td>
                                    <td>{{TEXT}}</td>            
                                </tr>
                                <tr>
                                    <td>Phone</td>
                                    <td>{{TEXT}}</td>
                                </tr>
                                <tr>
                                    <td>Contract#</td>
                                    <td>{{TEXT}}</td>
                                </tr>
            
                            </table>
                        </td>
                    </tr>
                </table>
            </div>**
The above HTML I am trying to convert to Docx

**Comment by Mohini89** [comment]
Also GrabzIt not able to render below HTML code in Docx.
```
<div style="padding:0 15px;" >
            <table width="100%">
                <tr>
                    <td class="f-b">Merchant Signature</td>
                    <td class="f-b">Owner Signature</td>                    
                </tr>
                <tr>
                    <td><div style="height: 60px;border: 1px solid #000;padding: 6px; width: 60%;"> <div style="border: 1px dotted;height: 100%;"></div></div></td>
                    <td><div style="height: 60px;border: 1px solid #000;padding: 6px; width: 60%;"> <div style="border: 1px dotted;height: 100%;"></div></div></td>     
                </tr>
                <tr>
                    <td style="padding: 10px;">
                        <div class="marg-text">Position:</div>
                    </td>
                    <td style="padding: 10px;">
                        <div class="marg-text">Position:</div>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px;">
                        <div class="marg-text">Name:</div>
                    </td>
                    <td style=" padding: 10px;">
                        <div class="marg-text">Name:</div>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px;">
                        <div class="marg-text">Date:</div>
                    </td>
                    <td style="padding: 10px;">
                        <div class="marg-text">Date:</div>
                    </td>
                </tr>
            </table>
        </div>
```

**Comment by GrabzIt** [comment]
Thanks for the detailed bug report. We have added it to our development queue. At the moment GrabzIt doesn't support nested tables or cells containing other HTML elements.

**Comment by GrabzIt** [comment]
We have triaged this case. We currently don't support drawing boxes in DOCX on purpose, unless it is a table cell border, this is to avoid turning documents into a mess. As HTML documents often contain many HTML elements with a border.

Below is an example of moving your border to the cell level instead.

```
<table width="100%">
    <tr>
        <td style="height: 60px;border: 1px solid #000;padding: 6px; width: 60%;"></td>
        <td style="height: 60px;border: 1px solid #000;padding: 6px; width: 60%;"></td>
    </tr>
</table>
```
At the moment nested tables are not supported. However they are now in our development list. If you don't want to wait you can however use rowspan and colspan to achieve something similar:

```
<table style="width:100%;text-align: left;">
                    <tr>
                        <td rowspan="5">
                            <div style="float:left;margin-top:123px;">
                                <div style="font-size:18px; font-weight:bold;text-decoration: underline;"> {{TEXT}}</div>
                                <div style="font-size:20px;"> {{TEXT}}:</div>
                            </div>
                        </td>
                    </tr>
                                <tr>
                                    <td>Account<br> Manager Name:</td>
                                    <td>{{TEXT}}</td>
                                </tr>
                                <tr>
                                    <td>Email</td>
                                    <td>{{TEXT}}</td>            
                                </tr>
                                <tr>
                                    <td>Phone</td>
                                    <td>{{TEXT}}</td>
                                </tr>
                                <tr>
                                    <td>Contract#</td>
                                    <td>{{TEXT}}</td>
                                </tr>					
                </table>
```

**Comment by GrabzIt** [comment]
GrabzIt's DOCX conversions now support nested tables!
