### ISSUE TITLE
Alignment issue with Docx

### ISSUE THREAD

**Issue by Mohini89** [GrabzIt/grabzit#21]
Hi Team,

Please help me to include the below html code properly in DOCx. The issue is these two tables are not aligned in the same rows instead the second table goes on the next line of DOCx file, however it works well while generating PDF.

`<div class="row" style="padding: 15px; width:100%">
                <div class="col-sm-4" style="width:50%;">
                    <h6>Accepted by the Merchant</h6>
                    <table cellspacing="7" style="width:60%;border: 1px solid;height: 70px;">
                        <tbody>
                        <tr>
                            <td style="border: 1px dotted;"></td>
                        </tr>
                    </tbody>
                    </table>
                    <div class="signature">Position:</div>
                    <div class="signature">Name:</div>
                    <div class="signature">Date:</div>
                </div>
                <div class="col-sm-4" style="width:50%;">
                    <h6>Accepted by VOUCHED4U</h6>
                    <table cellspacing="7" style="width:60%;border: 1px solid;height: 70px;">
                        <tbody>
                        <tr>
                            <td style="border: 1px dotted;"></td>
                        </tr>
                    </tbody>
                    </table>
                    <div class="signature">Position:</div>
                    <div class="signature">Name:</div>
                    <div class="signature">Date:</div>
                </div>
            </div>`

**Comment by GrabzIt** [comment]
Hi Mohini,

Are you saying you don't want those extra spaces and it should look like this?

[c3VwcG9ydEBncmFiei5pdA==-43b34d13ec844eb69a880eba0ee2d633d.docx](https://github.com/GrabzIt/grabzit/files/4096091/c3VwcG9ydEBncmFiei5pdA.-43b34d13ec844eb69a880eba0ee2d633d.docx)

**Comment by Mohini89** [comment]
<div class="col-sm-4" style="width:50%;"></div>
and the other <div class="col-sm-4" style="width:50%;"></div>

should be inline aligned. But This is rendered one below another.

![Picture2](https://user-images.githubusercontent.com/59864980/72880346-2d7e9000-3d18-11ea-90e4-da1b9b76ff77.png)

**Comment by GrabzIt** [comment]
The HTML you sent makes them go one after the other.

**Comment by Mohini89** [comment]
HTML displays content one after another which is correct. But when exported to DOCx looks wrong.

I have posted the previous image from the DOCx file sent by you.

![image](https://user-images.githubusercontent.com/59864980/72881379-180a6580-3d1a-11ea-9963-d09db1236040.png)

**Comment by GrabzIt** [comment]
This is what it looks like in HTML 
![html](https://user-images.githubusercontent.com/11035754/72881767-4f1c4f00-3cf9-11ea-9c45-2d7ee8a62220.png)

I know about the extra spaces from your initial HTML, and we have raised a case to fix this.

Is there anything else wrong from the conversion of your HTML? Please note that in DOCX there is no concept of [table cell height](https://grabz.it/support/?uniqueId=html-to-docx-supported-css).

**Comment by GrabzIt** [comment]
The spaces issue has been fixed and will be released soon.

**Comment by Mohini89** [comment]
Hi team,
Please see the difference between the HTML code content and the DOCx rendered content.
`<style>
     .children {
    float: left;
    clear: none; 
}
.signature {
    padding: 10px 10px 10px 0px;
  }
</style>
<div class="aParent" style="padding: 15px; width:100%">
    <div class="children" style="width:50%;">
        <h6>Accepted by the Merchant</h6>
        <table cellspacing="7" style="width:60%;border: 1px solid;height: 70px;">
            <tbody>
            <tr>
                <td style="border: 1px dotted;"></td>
            </tr>
        </tbody>
        </table>
        <div class="signature">Position:</div>
        <div class="signature">Name:</div>
        <div class="signature">Date:</div>
    </div>
    <div class="children" style="width:50%;">
        <h6>Accepted by VOUCHED4U</h6>
        <table cellspacing="7" style="width:60%;border: 1px solid;height: 70px;">
            <tbody>
            <tr>
                <td style="border: 1px dotted;"></td>
            </tr>
        </tbody>
        </table>
        <div class="signature">Position:</div>
        <div class="signature">Name:</div>
        <div class="signature">Date:</div>
    </div>
</div>`

**Comment by GrabzIt** [comment]
In docx we don't handle floating elements as it is not something that translates well to the DOCX format. However you can either use HTML tables or CSS columns: https://grabz.it/support/?uniqueId=html-to-docx-supported-css

https://www.w3schools.com/css/css3_multiple_columns.asp
