### ISSUE TITLE
Downloads but with incomplete data

### ISSUE THREAD

**Issue by Mohini89** [GrabzIt/grabzit#22]
Hi team,

I am using GrabzIT for downloading a content in 'Docx' as well as in 'PDF'. But One thing I observed is, download has been initiated before the page is loaded. However I don't how it works correctly for PDF but most of the times data on downloaded Docx is incomplete.

Is there a way, task of converting URI content to Docx or PDF to start only after the download URL has been loaded completely?

**Comment by GrabzIt** [comment]
This is not a place for support questions, please look at the support section of our website: https://grabz.it/support/index.aspx?uniqueId=delaying-web-captures
