### ISSUE TITLE
DOCx render issue

### ISSUE THREAD

**Issue by Mohini89** [GrabzIt/grabzit#29]
Hello team,

I am not able to render the webpage correctly to docx file.

Please find the below URL for your reference.
http://v4udev.com/tableqrcode/5/0

**Comment by GrabzIt** [comment]
What's wrong with it, ut looks quite accurate to me.

**Comment by Mohini89** [comment]
Page is fine, but what I see is [
[c2027ebc-08da-4439-a078-c59dc4f620a7.docx](https://github.com/GrabzIt/grabzit/files/5080546/c2027ebc-08da-4439-a078-c59dc4f620a7.docx)
](url)

**Comment by GrabzIt** [comment]
You don't get the same alignment in docx as its not a webpage. It doesn't handle absolute positioning wtc.

**Comment by Mohini89** [comment]
but it renders on PDF correctly and not on DOCx

**Comment by GrabzIt** [comment]
I believe i have mentioned this to you before PDF uses absolute positioning. DOCX doesn't. That's why PDF can do it almost perfectly most if the time. Tgis is hust how the file formats work.
