### ISSUE TITLE
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)

### ISSUE THREAD

**Issue by laceyrkeller** [GrabzIt/grabzit#33]
Hi all! WE LOVE GRABZIT and are getting this error.

**Comment by GrabzIt** [comment]
We use LetsEncrypt for our https certificates which until the 30th of September was using a old root certificate this has now been ported over to more secure version by LetsEncrypt.

If you want to continue accessing our API via https you will need to update the certificates used by your system, alternatively you can disable HTTPS when accessing our API. There is an option to do so on all our libraries.

More information can be found here: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
