### ISSUE TITLE
Circular import in python

### ISSUE THREAD

**Issue by dapsvi** [GrabzIt/grabzit#46]
I installed the module using pip.

Then, I tried this simple test in python :
```py
from GrabzIt import GrabzItClient, GrabzItVideoOptions
API_KEY = "you-will-never-guess"
API_SECRET = "you-will-never-guess-as-well"

def download_image(html_content, filename):
    grabzIt = GrabzItClient.GrabzItClient(API_KEY, API_SECRET)
    grabzIt.HTMLToImage(html_content)
    grabzIt.SaveTo(f"./screenshots/{filename}")

download_image("<h1>foo</h1>", "test.jpg")
```

Here is the error message :
```
ImportError: cannot import name 'GrabzItVideoOptions' from partially initialized module 'GrabzIt' (most likely due to a circular import) (C:\Users\Utilisateur\AppData\Roaming\Python\Python310\site-packages\GrabzIt\__init__.py)
```

I thought it was due to the names of the other python files in the current directory, but I don't know which ones I have to rename. Here is the list :
- config.py
- imgen.py
- main.py
- models.py
- prompt.py
- downloader.py (current file)

Thanks in advance !

**Comment by GrabzIt** [comment]
Hi,

I think GrabzItVideoOptions is already imported by the GrabzItClient so I don't think you need to import it again.

Hopefully that's the problem.

Regards,

The GrabzIt Team

**Comment by dapsvi** [comment]
Sorry, I forgot to remove the second import but it raises the same error without it (by only importing GrabzItClient)

**Comment by GrabzIt** [comment]
Thanks for reporting this.

Please can you tell us the python version you are using?

I think the import for GrabzItVideoOptions is missing from here: https://github.com/GrabzIt/grabzit/blob/master/python/GrabzIt/__init__.py

Our developer is on leave until Monday so won't be able to do a pip release until then.

You could download the code make the fix suggested until the change is pushed to pip. Or use the REST API.

I am sorry for the inconvenience.

**Comment by dapsvi** [comment]
Sure !
```
>>> import sys
>>> sys.version
'3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]'
>>>
```
I am going to make a simple implementation of the REST API for my needs.
