### ISSUE TITLE
[Python] GrabzItClient instance has no attribute 'GetPicture'

### ISSUE THREAD

**Issue by edent** [GrabzIt/grabzit#8]
Running a very simple example in Python, I get this error message:

```
Traceback (most recent call last):
  File "grab.py", line 8, in <module>
    grabzIt.SaveTo("testgrab.png") 
  File "/usr/local/lib/python2.7/dist-packages/GrabzIt/GrabzItClient.py", line 198, in SaveTo
    result = self.GetPicture(id)
AttributeError: GrabzItClient instance has no attribute 'GetPicture'
```

Seems to be at https://github.com/GrabzIt/grabzit/blob/af2dd7de8ccdcacdda2bc12cb0ec3e122c484657/python/GrabzIt/GrabzItClient.py#L198

Happens with any URL I throw at it.  My code is (keys redacted)

```
from GrabzIt import GrabzItClient
grabzIt = GrabzItClient.GrabzItClient("...", "...")
grabzIt.URLToImage("https://twitter.com/visionOntv/status/792403836199641088") 	
grabzIt.SaveTo("testgrab.png") 
```

**Comment by GrabzIt** [comment]
Thanks for raising this issue. We will release a fix soon. However if you want to fix it on your version replace GetPicture with GetResult
